### ISSUE TITLE
Logger failes to initialize when not providing the Classic Logback Logger in 0.45.0 

### ISSUE THREAD

**Issue by ZacSweers** [pinterest/ktlint#1421]
## Expected Behavior

It should work

## Observed Behavior

This failure occurs (when using via Spotless)

```
Step 'ktlint' found problem in 'src/main/java/slack/appprofile/di/AppProfileModule.kt':
--
  | Could not initialize class com.pinterest.ktlint.core.internal.EditorConfigLoaderKt
  | java.lang.NoClassDefFoundError: Could not initialize class com.pinterest.ktlint.core.internal.EditorConfigLoaderKt
  | at com.pinterest.ktlint.core.internal.EditorConfigLoader.loadPropertiesForFile(EditorConfigLoader.kt:111)
  | at com.pinterest.ktlint.core.KtLint.prepareCodeForLinting(KtLint.kt:234)
  | at com.pinterest.ktlint.core.KtLint.format(KtLint.kt:344)
  | at com.pinterest.ktlint.core.KtLint.format(KtLint.kt:319)
  | at com.pinterest.ktlint.core.KtLint.format(KtLint.kt:315)
  | at com.diffplug.spotless.glue.ktlint.KtlintFormatterFunc.applyWithFile(KtlintFormatterFunc.java:60)
  | at com.diffplug.spotless.FormatterFunc$NeedsFile.apply(FormatterFunc.java:154)
  | at com.diffplug.spotless.FormatterStepImpl$Standard.format(FormatterStepImpl.java:78)
  | at com.diffplug.spotless.FormatterStep$Strict.format(FormatterStep.java:88)
  | at com.diffplug.spotless.Formatter.compute(Formatter.java:230)
  | at com.diffplug.spotless.PaddedCell.calculateDirtyState(PaddedCell.java:203)
  | at com.diffplug.spotless.PaddedCell.calculateDirtyState(PaddedCell.java:190)
  | at com.diffplug.gradle.spotless.SpotlessTaskImpl.processInputFile(SpotlessTaskImpl.java:92)
  | at com.diffplug.gradle.spotless.SpotlessTaskImpl.performAction(SpotlessTaskImpl.java:78)
```

## Steps to Reproduce

Use editorconfig and ktlint 0.45.0 in a project

## Your Environment

* Version of ktlint used: 0.45.0
* Relevant parts of the `.editorconfig` settings
```toml
[*]
charset=utf-8
end_of_line=lf
insert_final_newline=true
trim_trailing_whitespace=true
indent_style=space
indent_size=4

[*.proto]
indent_size=2

[*.java]
indent_size=2

[*.json]
indent_size=2

[*.{kt,kts}]
indent_size=2
continuation_indent_size=2
disabled_rules=final-newline

[{*.yml,*.yaml}]
indent_size=2
```
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task): Spotless 6.3.0
* Version of Gradle used (if applicable): 7.4.1
* Operating System and version: macOS Monterey
