### ISSUE TITLE
Add pre-commit configuration

### ISSUE THREAD

**Issue by Goldziher** [pinterest/ktlint#2258]
Hi there,

It would be awesome to use ktlint via [pre-commit](https://pre-commit.com). There are unofficial tools for this, but an official hook would be much better.

**Comment by paul-dingemans** [comment]
Please, see https://pinterest.github.io/ktlint/1.0.0/install/cli/#git-hooks

**Comment by Goldziher** [comment]
well, i use pre-commit as an orchestrator for lining in a polyglot monorepo, this is not a solution really.

**Comment by Goldziher** [comment]
For anyone that comes to this issue, my solution is as follows. 

Add a file under `.bin/ktlint.sh` with the following:

```shell
#!/bin/bash

if ! command -v ktlint &> /dev/null
then
    if command -v brew &> /dev/null
    then
        brew install ktlint
    elif command -v scoop &> /dev/null
    then
        scoop install ktlint
    else
      echo "ktlint could not be found, please install it on your system by following the instructions here: https://pinterest.github.io/ktlint/1.0.0/install/cli/"
      exit
    fi
fi

fileArray=("$@")
ktlintInput=$(IFS=,;printf  "%s" "${fileArray[*]}")
OUTPUT=$(ktlint --experimental "$ktlintInput" 2>&1)
EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
  printf "%s" "$OUTPUT"
  exit $EXIT_CODE
fi
```

I obviously use MacOS for development, so adjust it as required for your needs.

Then add the following configs in pre-commit:

```yaml
    - repo: local
      hooks:
          - id: ktlint
            name: ktlint
            description: Runs `ktlint` on modified .kt files.
            language: script
            entry: .bin/ktlint.sh
            files: \.kt
```

@paul-dingemans - this would be great If it could be included in the main repo, or at least in the docs since [pre-commit](https://pre-commit.com/) is a very popular tool - and i use it to run a monorepo.
